### ISSUE TITLE
Refactor: reusable buttons

### ISSUE THREAD

**Issue by AnnaSolovykh** [JULIERAJ/KIDS-FIRST-Front#10]
**Requirements**
- Customs buttons should be reusable
- Design of the buttons should be updated according to [Figma](https://www.figma.com/design/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=501-3083&t=eLLYUujZyqokFEVQ-0)

![Image](https://github.com/JULIERAJ/KIDS-FIRST-Front/assets/114008959/f57c7ade-4989-47f6-9cb3-2262a33a9b1d)

**Comment by AnnaSolovykh** [comment]
@nandini92 changed the size, added the buttons styling :sparkles:

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
