### ISSUE TITLE
Bug: Icons added to custom button does not change color on hover/focus

### ISSUE THREAD

**Issue by nandini92** [JULIERAJ/KIDS-FIRST-Front#104]
Icon added to custom button does not change color on hover or focus:

![Image](https://github.com/user-attachments/assets/6f1744ca-f6d0-40a1-9957-ad5d77f1a4e8)

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
