### ISSUE TITLE
Refactor: lifting state in SignIn and Register

### ISSUE THREAD

**Issue by AnnaSolovykh** [JULIERAJ/KIDS-FIRST-Front#16]
This is a 'kid' of the bigger task. [You can find more info on this topic by this link](https://github.com/users/JULIERAJ/projects/2/views/1?pane=issue&itemId=67877295). 

**Requirement**
- Create handler function(s) in the parent component to avoid setting state in the child component. The state should be managed in the parent component.

![Image](https://github.com/JULIERAJ/KIDS-FIRST-Front/assets/114008959/3672a3e5-7407-4c3d-911f-2239317cb69d)

![Image](https://github.com/JULIERAJ/KIDS-FIRST-Front/assets/114008959/7d7264e8-5098-48f0-bfdf-c0437e7ade06)

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
