### ISSUE TITLE
Frontend: setup axios interceptors

### ISSUE THREAD

**Issue by ElenaCherpakova** [JULIERAJ/KIDS-FIRST-Front#39]
### Implement Global Axios Interceptors for Authorization and Authentication
[Docs](https://axios-http.com/docs/interceptors)

**Description:**

Implement Axios interceptors to globally handle authorization and authentication across all API requests. The interceptors should automatically attach tokens to outgoing requests and handle responses to check for authorization and authentication status.

**Tasks**:

**1. Set Up Axios Interceptors**
- Configure an Axios instance with request and response interceptors.
- Attach JWT authentication token to outgoing requests.
- Handle authorization errors in responses (e.g., redirect to login on 401 status).

**2. Integrate Axios Instance Globally**
- Replace existing Axios instances with the globally configured instance.
- Ensure all API calls use the new instance with interceptors.

**3. Error Handling and Redirects**
- Implement error handling for failed requests due to authentication or authorization issues.
- Redirect users to the login page if they are not authenticated.

**4. Testing**
- Test the Axios interceptors to ensure they correctly attach tokens and handle errors.
- Verify that the application redirects to the login page when necessary.

**Acceptance Criteria:**
[] Axios interceptors are implemented to handle authentication and authorization globally.
[] Tokens are automatically attached to outgoing requests.
[] Application redirects to the login page on authentication or authorization errors.
[] All API calls use the globally configured Axios instance.

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
