### ISSUE TITLE
Fix: password changed page

### ISSUE THREAD

**Issue by AnnaSolovykh** [JULIERAJ/KIDS-FIRST-Front#46]
**Requirements** 
- Adjust password changed page to match the design in Figma. 
- Follow the best practices while accomplishing the task. 
- Follow the measurements in Figma

Current looks: 
 _Password changed Page_
![Image](https://github.com/user-attachments/assets/243fb86d-c61e-445a-be87-bca0f9f5c4ea)

[Figma](https://www.figma.com/design/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=0-1&t=tOvhcRhGNw9ponl6-0)
![Image](https://github.com/user-attachments/assets/9b3d931e-1375-4c6c-8a10-db9725170eed)

![Image](https://github.com/user-attachments/assets/1ca085c5-1d9b-4698-ad2b-434db314ac95)

![Image](https://github.com/user-attachments/assets/22ff97b5-1a42-4c74-858a-66696561368a)

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
