### ISSUE TITLE
Feature: update landing page

### ISSUE THREAD

**Issue by AnnaSolovykh** [JULIERAJ/KIDS-FIRST-Front#59]
**Requirements**
- The landing page should be updated to match the new version of the app
[Figma](https://www.figma.com/design/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=0-1&t=u5L6WjfMHRlgXlnu-0)

![Image](https://github.com/user-attachments/assets/61977d70-d327-44be-babe-a8a15ac556dc)

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
