### ISSUE TITLE
HOTFIX: fix axios interseptors

### ISSUE THREAD

**Issue by AnnaSolovykh** [JULIERAJ/KIDS-FIRST-Front#76]
If you try to open Link expired page or Something went wrong you get this kind of error. 
 
Testing Instruction: send a verification link, then resend it, and open the previous one - this is how you get to Link Expired page.
![Image](https://github.com/user-attachments/assets/71e0af72-b3cb-4467-9bea-e3fcc859002b)

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
