### ISSUE TITLE
Frontend/HOTFix: Overlapping on Kids Logo on hover of Home section

### ISSUE THREAD

**Issue by ElenaCherpakova** [JULIERAJ/KIDS-FIRST-Front#82]
Needs to be corrected

![Screen Shot 2024-08-12 at 2 45 13 PM](https://github.com/user-attachments/assets/f7a48092-d6b3-49f6-912a-3ea28c252da6)

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
