### ISSUE TITLE
Fix: password reset minor flow fixes

### ISSUE THREAD

**Issue by nandini92** [JULIERAJ/KIDS-FIRST-Front#85]
- Confirm what layout we should have when we use the already used reset password link
![Image](https://github.com/user-attachments/assets/1b44af67-9da9-4b5d-8b8c-f87632f75778)

- Fix error location and design
![Image](https://github.com/user-attachments/assets/f6f756ee-2716-43df-88f1-36cd5f819c4e)

[Nandini]  Confirmed with Victoria to make the following page generic and use this if reset-password link has already been used:
![Image](https://github.com/user-attachments/assets/3367dedb-49b1-4fe2-8bad-d5c04ce717e9)

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
