### ISSUE TITLE
frontend: module window choose kid color

### ISSUE THREAD

**Issue by ElenaCherpakova** [JULIERAJ/KIDS-FIRST-Front#86]
Creating popup window for choosing kid color
![Image](https://github.com/user-attachments/assets/1ae67cd1-c683-4e6b-9c43-11eb6ba90637)

[Figma link](https://www.figma.com/design/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=0-1&t=wyEviTlg3rYgoZAo-0)

**Comment by nandini92** [comment]
Taking over from Ekaterina's existing branch.
