### ISSUE TITLE
Feat: Logout Layout/Endpoint Connect

### ISSUE THREAD

**Issue by AnnaSolovykh** [JULIERAJ/KIDS-FIRST-Front#9]
**Requirement**
1. Add Logout button
2. Connect Logout to the relevant endpoint
[Figma](https://www.figma.com/design/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=10237-60866&t=TaqmpGbwHurZT1EP-0)
![Image](https://github.com/JULIERAJ/KIDS-FIRST-Front/assets/114008959/e877409a-3b26-4cc4-ab53-5acf0e177201)

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
